# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule: # Check for updates once a week
      interval: "weekly"
    target-branch: "main" # Branch to create pull requests against
  # Enable version updates for pip e.g requirements.txt
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    allow:
      - dependency-type: "direct" # Allow direct packages updates
    schedule: # Check for updates once a week
      interval: "weekly"
    target-branch: "main" # Branch to create pull requests against
