site_name: Opulo Documentation
site_url: https://docs.opulo.io/
repo_url: https://github.com/opulo-inc/lumenpnp/
edit_uri: https://github.com/opulo-inc/docs/edit/main/docs

extra_css: 
    - stylesheets/extra.css
    - stylesheets/neoteroi-cards.css

markdown_extensions:
    - admonition
    - def_list
    - pymdownx.superfences
    - attr_list
    - md_in_html
    - neoteroi.cards
    - meta
    - footnotes
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
    

theme:
    name: material
    logo: img/opulo.png
    favicon: img/favicon.ico
    font:
        text: Figtree
    features:
        # Turning off footer nav as it can be misleading, and we have explicit links to the appropriate next section for every page
        #- navigation.footer
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - content.tabs.link
        - content.action.edit
        - toc.integrate
        - content.code.copy

    palette: 
        #primary: custom
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: custom
          accent: custom
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          primary: custom
          accent: custom
          scheme: default 
          toggle:
            icon: material/brightness-7 
            name: Switch to dark mode
plugins:
    - glightbox:
        draggable: false
    - search 
    - social:
        cards_layout_options:
            background_color: "#111111" 
            color: "#daa520"
            font_family: Figtree 
    - neoteroi.mkdocsoad:
        use_pymdownx: true
extra:
  social:
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/opuloinc
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OpuloInc
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/opulo.io
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCMf49SMPnhxdLormhEpfyfg
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/TCwy6De
nav:
    - Home: index.md
    - LumenPnP Assembly:
        - LumenPnP v4: 
            - Introduction: semi-assembly-4-0/index.md
            - Unboxing: semi-assembly-4-0/unboxing/index.md
            - Frame: semi-assembly-4-0/frame/index.md
            - Electronics: semi-assembly-4-0/electronics/index.md
        - LumenPnP v3.1 / v3.2: 
            - Introduction: semi-assembly-3-1/index.md
            - Unboxing: semi-assembly-3-1/unboxing-3-1/index.md
            - Assembling the Frame: semi-assembly-3-1/assembling-frame-3-1/index.md
            - Mounting Staging Plates: semi-assembly-3-1/mounting-staging-plates-3-1/index.md
            - Wiring: semi-assembly-3-1/wiring-3-1/index.md
        - LumenPnP v3.0: 
            - Introduction: semi-assembly/index.md
            - Unboxing: semi-assembly/unboxing/index.md
            - Assembling the Frame: semi-assembly/assembling-frame/index.md
            - Mounting Staging Plates: semi-assembly/mounting-staging-plates/index.md
            - Wiring: semi-assembly/wiring/index.md
        - Kit Assembly (v2): 
            - Introduction: byop/index.md
            - Mechanical Assembly:
                - Printing Parts: byop/mechanical-assembly/1-printing-parts/index.md
                - Belt Tensioners: byop/mechanical-assembly/2-belt-tensioners/index.md
                - Left Side: byop/mechanical-assembly/3-left-side/index.md
                - Right Side: byop/mechanical-assembly/4-right-side/index.md
                - Connecting the Sides: byop/mechanical-assembly/5-connecting-sides/index.md
                - Y Gantry Assembly: byop/mechanical-assembly/6-y-gantry-assembly/index.md
                - X Gantry Assembly: byop/mechanical-assembly/7-x-gantry-assembly/index.md
                - Mounting X Gantry to Y: byop/mechanical-assembly/8-mount-x-to-y/index.md
                - Mount Y Gantry to Frame: byop/mechanical-assembly/9-mount-y-to-frame/index.md
                - Attaching Belts: byop/mechanical-assembly/10-attaching-belts/index.md
                - Populating the Staging Plate: byop/mechanical-assembly/11-populating-staging-plate/index.md
            - Motherboard Installation:
                - Install THT: byop/motherboard/installing-tht/index.md
                - Mounting the Motherboard: byop/motherboard/mounting/index.md
            - Wiring and Pneumatics:
                - Wiring the Y Motors: byop/wiring-and-pneumatics/wiring-y-motors/index.md
                - Sheathing the Umbilicals: byop/wiring-and-pneumatics/sheathing-umbilicals/index.md
                - Routing Y Gantry Umbilical: byop/wiring-and-pneumatics/routing-y-umbilical/index.md
                - Routing X Gantry Umbilical: byop/wiring-and-pneumatics/routing-x-umbilical/index.md
                - Connecting to the Motherboard: byop/wiring-and-pneumatics/connecting-to-mobo/index.md
                - Connecting Pneumatics: byop/wiring-and-pneumatics/connecting-pneumatics/index.md
            - Testing:
                - Connect to the Computer: byop/testing/connect-computer/index.md
                - Motor Check: byop/testing/motor-check/index.md
                - Actuator Check: byop/testing/actuator-check/index.md
                - Feedback: byop/testing/feedback/index.md
    - OpenPnP:
        - Install and Config: 
              - Install OpenPnP: openpnp/install-config/install/index.md
              - Import Configuration: openpnp/install-config/import-config/index.md
        - Calibration:
              - Introduction: openpnp/calibration/index.md
              - Connecting to Your Machine: openpnp/calibration/2-connect-to-machine/index.md
              - Homing Fiducial: openpnp/calibration/4-homing-fiducial/index.md
              - MM/Pixel: openpnp/calibration/5-mm-per-pixel/index.md
              - Nozzle Offset: openpnp/calibration/6-nozzle-offset/index.md
              - Bottom Camera Position: openpnp/calibration/7-bottom-camera-position/index.md
              - Nozzle Tip Calibration: openpnp/calibration/8-nozzle-tip-calibration/nozzle-tip-calibration.md
              - Vacuum Part Detection: openpnp/calibration/10-vacuum-sensor/index.md
        - Running Your First Job: 
              - Introduction: openpnp/ftp/index.md
              - Board Setup: openpnp/ftp/1-board-setup/index.md
              - Feeder Setup: openpnp/ftp/2-feeder-setup/index.md
              - Test Run: openpnp/ftp/3-test-run/index.md
        - Debugging: openpnp/debugging/index.md
        - Vision Pipeline Adjustment:
            - Introduction: openpnp/vision-pipeline-adjustment/1-introduction.md
            - Homing Fiducial Pipeline: openpnp/vision-pipeline-adjustment/2-homing-fiducial-pipeline.md
            - PCB Fiducial Pipeline: openpnp/vision-pipeline-adjustment/3-pcb-fiducial-pipeline.md
            - Nozzle Calibration Pipeline: openpnp/vision-pipeline-adjustment/4-nozzle-calibration-pipeline.md
            - Part Identification Pipeline: openpnp/vision-pipeline-adjustment/5-part-identification-pipeline.md
        - Next Steps: openpnp/next-steps/index.md
    - Feeders:
        - Overview: feeders/1-overview/feeder-overview.md
        - Installing the Slot Harness:
            - Introduction: feeders/2-install-harness/index.md
            - Slot Blades: feeders/2-install-harness/feeder-blade/index.md
            - Individual Slots: feeders/2-install-harness/feeder-slot/index.md
        - Software Update: feeders/3-software-update/index.md
        - Mounting Feeders: feeders/4-mounting/mounting.md
        - OpenPnP Setup: feeders/5-openpnp-setup/feeder-openpnp-setup.md
        - Loading Tape: feeders/6-loading-tape/loading-tape.md
        - Setting Pick Position: feeders/7-setting-pick-position/setting-pick-position.md
        - Troubleshooting: feeders/8-troubleshooting/troubleshooting.md
  
    - Guides: 
        - Update LumenPnP Firmware: guides/update-firmware/index.md
        - Updating OpenPnP GCode Macros: guides/update-gcode-macros/index.md
        - Change Motor Current: guides/motor-current/index.md
        - Change Machine Speed: guides/machine-speed/index.md
        - Change Ring Light Brightness: guides/ring-light-settings/index.md
        - Tune Sensorless Homing: guides/tuning-sensorless/index.md
        - Set Motor Disable Timeout: guides/motor-disable-timeout/index.md
        - Second Nozzle Upgrade Guide: guides/second-tool/index.md
        - REV03 Mobo Interposer Guide: guides/rev3-vac-interposer/index.md
        - Collecting OpenPnP Logs: guides/openpnp-logs/index.md
        - Find Your OpenPnP Version: guides/get-openpnp-version/index.md
        - Extracting Your Config Files: guides/extracting-your-config-files/index.md
    
    - Misc:
        - Machine Versions and Upgrades: misc/versions-upgrades/index.md
        - Backlash Compensation: misc/backlash-compensation/index.md
        - Standalone Feeder Control: misc/standalone-feeders/index.md
        - Photon Protocol: misc/photon/index.md

    - FAQ: faq/index.md

    - Design for LumenPnP: design-for-lumenpnp/index.md

