site_name: Opulo Documentation
site_url: https://docs.opulo.io/
repo_url: https://github.com/opulo-inc/lumenpnp/
edit_uri: https://github.com/opulo-inc/docs/edit/main/docs

extra_css: [stylesheets/extra.css]

markdown_extensions:
    - admonition
    - def_list
    - pymdownx.superfences
    - footnotes
    - pymdownx.tabbed:
        alternate_style: true
    - attr_list
    - md_in_html

theme:
    name: material
    logo: img/opulo.png
    favicon: img/favicon.ico
    font:
        text: Roboto
    features:
        - navigation.footer
        - navigation.tracking
        - content.tabs.link
        - content.action.edit

    palette: 
        #primary: custom
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: custom
          accent: custom
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          primary: custom
          accent: custom
          scheme: default
          toggle:
            icon: material/brightness-7 
            name: Switch to dark mode



plugins:
   - glightbox:
        draggable: false
nav:
    - Home: index.md
    - LumenPnP Assembly:
        - Semi Assembly (v3.1): 
            - Introduction: semi-assembly-3-1/index.md
            - Unboxing: semi-assembly-3-1/unboxing-3-1/index.md
            - Assembling the Frame: semi-assembly-3-1/assembling-frame-3-1/index.md
            - Mounting Staging Plates: semi-assembly-3-1/mounting-staging-plates-3-1/index.md
            - Wiring: semi-assembly-3-1/wiring-3-1/index.md
        - Semi Assembly (v3.0): 
            - Introduction: semi-assembly/index.md
            - Unboxing: semi-assembly/unboxing/index.md
            - Assembling the Frame: semi-assembly/assembling-frame/index.md
            - Mounting Staging Plates: semi-assembly/mounting-staging-plates/index.md
            - Wiring: semi-assembly/wiring/index.md
        - Kit Assembly (v2): 
            - Introduction: byop/index.md
            - Mechanical Assembly:
                - Printing Parts: byop/mechanical-assembly/1-printing-parts/index.md
                - Belt Tensioners: byop/mechanical-assembly/2-belt-tensioners/index.md
                - Left Side: byop/mechanical-assembly/3-left-side/index.md
                - Right Side: byop/mechanical-assembly/4-right-side/index.md
                - Connecting the Sides: byop/mechanical-assembly/5-connecting-sides/index.md
                - Y Gantry Assembly: byop/mechanical-assembly/6-y-gantry-assembly/index.md
                - X Gantry Assembly: byop/mechanical-assembly/7-x-gantry-assembly/index.md
                - Mounting X Gantry to Y: byop/mechanical-assembly/8-mount-x-to-y/index.md
                - Mount Y Gantry to Frame: byop/mechanical-assembly/9-mount-y-to-frame/index.md
                - Attaching Belts: byop/mechanical-assembly/10-attaching-belts/index.md
                - Populating the Staging Plate: byop/mechanical-assembly/11-populating-staging-plate/index.md
            - Motherboard Installation:
                - Install THT: byop/motherboard/installing-tht/index.md
                - Mounting the Motherboard: byop/motherboard/mounting/index.md
                - Updating Firmware: byop/motherboard/update-firmware/index.md
            - Wiring and Pneumatics:
                - Wiring the Y Motors: byop/wiring-and-pneumatics/wiring-y-motors/index.md
                - Sheathing the Umbilicals: byop/wiring-and-pneumatics/sheathing-umbilicals/index.md
                - Routing Y Gantry Umbilical: byop/wiring-and-pneumatics/routing-y-umbilical/index.md
                - Routing X Gantry Umbilical: byop/wiring-and-pneumatics/routing-x-umbilical/index.md
                - Connecting to the Motherboard: byop/wiring-and-pneumatics/connecting-to-mobo/index.md
                - Connecting Pneumatics: byop/wiring-and-pneumatics/connecting-pneumatics/index.md
            - Testing:
                - Connect to the Computer: byop/testing/connect-computer/index.md
                - Motor Check: byop/testing/motor-check/index.md
                - Actuator Check: byop/testing/actuator-check/index.md
                - Feedback: byop/testing/feedback/index.md
    - OpenPnP:
        - Introduction: openpnp/index.md
        - Calibration:
              - Getting Started: openpnp/calibration/index.md
              - Importing Configuration: openpnp/calibration/1-import-config/index.md
              - Connecting to Your Machine: openpnp/calibration/2-connect-to-machine/index.md
              - Homing Fiducial: openpnp/calibration/4-homing-fiducial/index.md
              - MM/Pixel: openpnp/calibration/5-mm-per-pixel/index.md
              - Nozzle Offset: openpnp/calibration/6-nozzle-offset/index.md
              - Bottom Camera Position: openpnp/calibration/7-bottom-camera-position/index.md
              - Nozzle Tip Calibration: openpnp/calibration/8-nozzle-tip-calibration/nozzle-tip-calibration.md
              - Backlash Compensation: openpnp/calibration/8-backlash-compensation/index.md
              - Automatic Toolchanger: openpnp/calibration/9-auto-toolchanger/index.md
              - Vacuum Part Detection: openpnp/calibration/10-vacuum-sensor/index.md
        - Running Your First Job: 
              - Introduction: openpnp/ftp/index.md
              - Installing Feeders: openpnp/ftp/1-installing-the-feeders/index.md
              - Setting Up the Board: openpnp/ftp/2-setting-up-the-board/index.md
        - Next Steps: openpnp/next-steps/index.md
        - Vision Pipeline Adjustment:
            - Introduction: openpnp/vision-pipeline-adjustment/1-introduction.md
            - Homing Fiducial Pipeline: openpnp/vision-pipeline-adjustment/2-homing-fiducial-pipeline.md
            - PCB Fiducial Pipeline: openpnp/vision-pipeline-adjustment/3-pcb-fiducial-pipeline.md
            - Nozzle Calibration Pipeline: openpnp/vision-pipeline-adjustment/4-nozzle-calibration-pipeline.md
            - Part Identification Pipeline: openpnp/vision-pipeline-adjustment/5-part-identification-pipeline.md
    - Feeders:
        - Overview: feeders/1-overview/feeder-overview.md
        - Installing the Slot Harness: feeders/2-install-harness/installing-the-slot-harness.md
        - Software Update: feeders/3-software-update/software-update.md
        - Mounting Feeders: feeders/4-mounting/mounting.md
        - OpenPnP Setup: feeders/5-openpnp-setup/feeder-openpnp-setup.md
        - Loading Tape: feeders/6-loading-tape/loading-tape.md
        - Setting Pick Position: feeders/7-setting-pick-position/setting-pick-position.md
        - Troubleshooting: feeders/8-troubleshooting/troubleshooting.md
        
    - Misc:
        - Troubleshooting: 
              - Symptoms: misc/troubleshooting/symptoms/index.md
              - Solutions: misc/troubleshooting/solutions/index.md
              - Diagnostic Routines: misc/troubleshooting/diagnostic-routines/index.md
        - Maintenance and Upgrades: 
              - REV03 Mobo Interposer Guide: misc/maintenance-upgrades/rev3-vac-interposer/index.md
              - Second Nozzle Upgrade Guide: misc/maintenance-upgrades/second-tool/index.md
              - Standalone Feeder Control: misc/maintenance-upgrades/standalone-feeders/index.md

