name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: sudo apt-get install imagemagick pngquant
      - run: find . -name '*.png' -execdir bash -c 'mogrify -resize 750x "$1"' - {} \;
      - run: find . -name '*.png' -execdir bash -c 'pngquant "$1" --ext .png --force' - {} \;
      - run: mkdocs gh-deploy --force
